
name: tox-kz6fittycent # check to see if it's available
version: '3.0.0.3+git' # check versioning
summary: tox aims to automate and standardize testing in Python # 79 char long summary
description: |
    tox aims to automate and standardize testing in Python. It is part of a larger vision of easing the packaging, testing and release process of Python software.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs

apps:
  tox:
    aliases: 
      - tox
    command: tox
    environment: 
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      - network-bind
     
parts: 
  my-part:
    source: https://github.com/kz6fittycent/tox
    source-type: git
    plugin: python
    
    build-packages:
      - python3
      
    stage-packages:
      - python3
